name: Update EPG

on:
  schedule:
    - cron: '0 3 * * *'
      timezone: 'Europe/Stockholm'
  workflow_dispatch:

jobs:
  grab-epg:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Krävs för att GitHub-boten ska kunna pusha filen
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Clone iptv-org/epg
      run: git clone --depth 1 https://github.com/iptv-org/epg.git epg-grabber

    - name: Install dependencies
      run: |
        cd epg-grabber
        npm install

    - name: Grab EPG
      run: |
        cd epg-grabber
        npm run grab -- --channels=../my_channels.xml

    - name: Move guide to root
      run: |
        mv epg-grabber/guide.xml ./guide.xml

    - name: Commit and Push
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # Öka buffertstorlek rejält för att hantera stora filer
        git config --global http.postBuffer 524288000
        git config --global http.lowSpeedLimit 0
        git config --global http.lowSpeedTime 999999
        
        git add guide.xml
        
        # Kontrollera om ändringar finns
        if ! git diff --quiet --exit-code; then
          git commit -m "Update EPG guide.xml"
          # Pusha med retry om anslutningen bryts
          for i in {1..3}; do
            git push origin main && break || sleep 10
          done
        else
          echo "Inga ändringar att committa."
        fi
